global:
  scrape_interval: 15s # How often to check for metrics

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # We will enable these in the next step, once Mule is configured
  # - job_name: 'mule-apis'
  #   metrics_path: '/api/metrics'
  #   static_configs:
  #     - targets: ['host.docker.internal:8081', 'host.docker.internal:8082']
